/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'haochen' at '12/23/15 2:56 PM' with Gradle 2.8
 *
 * @author haochen, @date 12/23/15 2:56 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
